name: Build and Publish

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build and test
        env:
          REPOS_PAT: ${{ secrets.REPOS_PAT }}
          # DinD environment: use Docker bridge gateway (172.17.0.1) with mapped ports
          # This allows the runner container to reach DinD containers via exposed ports
          TEST_MYSQL_HOST: 172.17.0.1
          TEST_MYSQL_PORT: 3307
          TEST_KAFKA_HOST: 172.17.0.1
          TEST_KAFKA_PORT: 9095
          TEST_APICURIO_HOST: 172.17.0.1
          TEST_APICURIO_PORT: 8082
        run: ./gradlew clean build --no-daemon

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: build/test-results/

      - name: Publish to Reposilite and Gitea
        if: gitea.ref == 'refs/heads/main'
        env:
          REPOS_PAT: ${{ secrets.REPOS_PAT }}
          GIT_USER: ${{ secrets.GIT_USER }}
          GIT_PAT: ${{ secrets.GIT_PAT }}
        run: ./gradlew publishMavenPublicationToMavenLocalRepository publishMavenPublicationToReposiliteRepository publishMavenPublicationToGiteaRepository --no-daemon

  docker:
    runs-on: ubuntu-latest
    needs: build
    if: gitea.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Gitea Container Registry
        uses: docker/login-action@v3
        with:
          registry: git.rokkon.com
          username: ${{ secrets.GIT_USER }}
          password: ${{ secrets.GIT_PAT }}

      - name: Build and push Docker image with Quarkus
        env:
          QUARKUS_CONTAINER_IMAGE_USERNAME: ${{ secrets.GIT_USER }}
          QUARKUS_CONTAINER_IMAGE_PASSWORD: ${{ secrets.GIT_PAT }}
          REPOS_PAT: ${{ secrets.REPOS_PAT }}
        run: |
          ./gradlew build -x test \
            -Dquarkus.container-image.build=true \
            -Dquarkus.container-image.push=true \
            -Dquarkus.container-image.additional-tags=${{ gitea.sha }} \
            --no-daemon
